import {build} from 'esbuild';
import {mkdir,copyFile,writeFile,rm,cp} from 'node:fs/promises';
await mkdir('docs',{recursive:true});
await rm('docs/chunks',{recursive:true,force:true});
await build({entryPoints:['src/app.js'],bundle:true,splitting:true,format:'esm',target:['safari17.4','chrome120'],outdir:'docs',entryNames:'app',chunkNames:'chunks/[name]-[hash]',minify:true,legalComments:'eof'});
await copyFile('src/index.html','docs/index.html');await copyFile('src/style.css','docs/style.css');
await rm('docs/image-tools',{recursive:true,force:true});
await cp('image-tools','docs/image-tools',{recursive:true});
await writeFile('docs/.nojekyll','');
await copyFile('node_modules/mediabunny/LICENSE','docs/mediabunny-LICENSE.txt');
await copyFile('node_modules/@mediabunny/aac-encoder/LICENSE','docs/aac-encoder-LICENSE.txt');
console.log('GitHub Pages output: docs/');
